 CREATE TABLE ADDRESS
 (
    ADDRESS_ID     INT        NOT NULL
    ,CITY          VARCHAR2(30)
    ,STATE         VARCHAR2(50)
    ,ZIP           INT 

    ,PRIMARY KEY (ADDRESS_ID)
 );

 CREATE TABLE STUDENT
 (
    STUDENT_ID         INT       NOT NULL
    ,FIRST_NAME        VARCHAR2(30)
    ,LAST_NAME         VARCHAR2(30)    
    ,PHONE             INT
    ,ADDRESS_ID        INT

    ,PRIMARY KEY (STUDENT_ID)
    ,CONSTRAINT STUDENT_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID)
 );


  CREATE TABLE COURSE
 (
    COURSE_ID      INT     NOT NULL
    ,DESCRIPTION   VARCHAR2(100)    NOT NULL
    ,COST          NUMBER(6,2)

    ,PRIMARY KEY (COURSE_ID)
 );


 CREATE TABLE ENROLLMENT
 (
    STUDENT_ID      INT     NOT NULL
    ,COURSE_ID      INT     NOT NULL

    ,UNIQUE KEY UN_KEY (STUDENT_ID,COURSE_ID)
 );